### ISSUE TITLE
关于菜单的问题

### ISSUE THREAD

**Issue by 123Windows31** [daizihan233/HanBot#17]
功能不写菜单先写的屑hantools

**Comment by daizihan233** [comment]
你具体想问啥

**Comment by 123Windows31** [comment]
没啥（）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "daizihan233/HanBot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月16日(星期三) 下午5:40
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [daizihan233/HanBot] 关于菜单的问题 (Issue #17)





 
你具体想问啥
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 123Windows31** [comment]
> 你具体想问啥

没啥（）关了吧
