### ISSUE TITLE
[Request]: 114514

### ISSUE THREAD

**Issue by SM-N770FZKGTGY** [daizihan233/HanBot#22]
### 请确定您做到了一下内容

- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 新功能名称

臭群

### 新功能描述

每天11：45am，pm定時發哼哼哼，啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by daizihan233** [comment]
后面跟几个“啊”？我想把他搞错一个随机数量的，你觉得多少到多少个合适？

**Comment by daizihan233** [comment]
Done.
