### ISSUE TITLE
新增復讀字詞

### ISSUE THREAD

**Issue by SM-N770FZKGTGY** [daizihan233/HanBot#38]
### 请确定您做到了一下内容

- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 功能名称

復讀v2.0

### 描述

增加字詞如：SM-114514,SM-N770F,SM-G770F,SM-HOMO1145141919810等

**Comment by daizihan233** [comment]
我的建议是：请把所有的要添加的列出来（

**Comment by SM-N770FZKGTGY** [comment]
> 我的建议是：请把所有的要添加的列出来（

啊哈哈，我想不到（
