### ISSUE TITLE
[Request]: 随机语录

### ISSUE THREAD

**Issue by Abjust** [daizihan233/HanBot#40]
### 请确定您做到了一下内容

- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 新功能名称

随机语录

### 新功能描述

at机器人输入随机语录，就从一言的api随机获取一条语录发出来

**Comment by SM-N770FZKGTGY** [comment]
雞你太美

**Comment by daizihan233** [comment]
在功能“鸡汤”中就是调用的这个接口
