### ISSUE TITLE
[Request++]: 删除部分复读字词

### ISSUE THREAD

**Issue by Abjust** [daizihan233/HanBot#45]
### 请确定您做到了以下内容

- [x] 我确定这是一个有意义的Issue，且目前没有此功能。

### 功能名称

删除部分复读字词

### 描述

建议把Millennium Force、Mako、Maverick、Magnum之类的有关过山车的，或者mf提出的复读字词删除，不仅没有任何作用，还让机器人沦为mf的刷屏机器

**Comment by MachineFuture** [comment]
不可能的事儿，**你想多了**

**Comment by Abjust** [comment]
就是你提的这个破意见吧？给机器人徒增压力，还屁用没有，机器人不能沦为你一个人的刷屏器！

**Comment by MachineFuture** [comment]
> 就是你提的这个破意见吧？给机器人徒增压力，还屁用没有，机器人不能沦为你一个人的刷屏器！

什么意思？**鸡你太美**

**Comment by daizihan233** [comment]
这边建议去提下 **PR** （

**Comment by Abjust** [comment]
> > 就是你提的这个破意见吧？给机器人徒增压力，还屁用没有，机器人不能沦为你一个人的刷屏器！
> 
> 什么意思？**鸡你太美**

你提的意见没几个有用的，全都是围绕你自己来的

**Comment by MachineFuture** [comment]
> 

### 你就是歌姬吧

**Comment by MachineFuture** [comment]
> 这边建议去提下 **PR** （

还不如`你连鸟都不要鸟他直接close怎么样`

**Comment by daizihan233** [comment]
> > 这边建议去提下 **PR** （
> 
> 还不如`你连鸟都不要鸟他直接close怎么样`

no

**Comment by daizihan233** [comment]
**PR已经合并至主分支并同步至服务器，这个Issue没有继续讨论的意义了**
