### ISSUE TITLE
復讀字詞新推薦

### ISSUE THREAD

**Issue by SM-N770FZKGTGY** [daizihan233/HanBot#47]
### 请确定您做到了以下内容

- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 新功能名称

復讀字詞新推薦

### 新功能描述

加入新字詞：寄，寄吧，屑，太草了，草草草，你就是個寄吧 By SM-N770FZKGTGY

**Comment by daizihan233** [comment]
请提交PR
