### ISSUE TITLE
面包功能bug

### ISSUE THREAD

**Issue by SM-N770FZKGTGY** [daizihan233/HanBot#49]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [x] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有解决方案。

### 重现步骤

假設面包庫存＝1024
兩個人發 来份面包 1024
＝@提問者 🍞*1024 @提問者 🍞*1024
@提問者
![Screenshot_20220717-165510_QQ](https://user-images.githubusercontent.com/98011222/179391449-dcbc4464-6cf9-4ab9-9cb3-97c343249ecd.jpg)
【错误】Sorry，您的订单量太大，库存仅有 -1024 份面包，请等一会儿

### 期望的结果是什么？

＝只有1024個包

### 实际的结果是什么？

實際上是-1024

**Comment by daizihan233** [comment]
这是因为HanBot使用了一个不安全的线程

**Comment by daizihan233** [comment]
现在要做的就是添加文件锁

由于HanBot部署于Windows Server，所以并没有Unix系统性的文件锁，换句话说现在必须手动实现文件锁

**Comment by daizihan233** [comment]
get_bread(): 共享锁
add_bread(): 排它锁

负值Bug已修好

新的Bug：有时还会取出2次，但最后的库存数值正常

**Comment by daizihan233** [comment]
现状：
![image](https://user-images.githubusercontent.com/72146468/179394539-5fd0e819-6faf-4cc4-97e8-f787f685e636.png)
![image](https://user-images.githubusercontent.com/72146468/179394541-b3d3aed2-ea42-4f09-bc6b-d9f59a91f54a.png)

~~当然我懒得修复这个Bug~~
_**这是特性**_
