### ISSUE TITLE
[Request++]: 把来个面包改为来包白象

### ISSUE THREAD

**Issue by 123Windows31** [daizihan233/HanBot#58]
### 请确定您做到了以下内容

- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 功能名称

来个面包

### 描述

2k提议将所有面包厂生产白象方便面，并把面包厂改名为方便面厂，所以我建议把来个面包功能改为来包白象

**Comment by 123Windows31** [comment]
1111111111111111111111111

**Comment by 123Windows31** [comment]
@daizihan233 @HanTools233 （

**Comment by daizihan233** [comment]
没意义 且你能在EMOJI里找到白象吗？（恼）
