### ISSUE TITLE
【公开处刑】 [Request]: 

### ISSUE THREAD

**Issue by huawei8888** [daizihan233/HanBot#59]
我是个傻逼！
我是个傻逼！
我是个傻逼！
我是个傻逼！
我是个傻逼！
### 请确定您做到了以下内容

- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 新功能名称

我是傻逼，我不配

### 新功能描述

我是傻逼，我不配

**Comment by daizihan233** [comment]
你他妈傻逼吧

**Comment by daizihan233** [comment]
公开处刑：上文被修改过，原文是：
---
请确定您做到了以下内容
  - [X] 我确定这是一个有意义的Issue，且目前没有此功能。
# 新功能名称

增加随机事件

# 新功能描述

什么？还需要我描述？我他妈****gun
---
我的评价是：依托答辩
